import initHeader from './header.js';
import initAbout from './about.js';
import initMaternity from './maternity.js';
import initTestimonials from './testimonials.js';
import initPhilosophy from './philosophy.js';
import initMemories from './memories.js';
import initScroll from './scroll.js';
import initShowcase from './revealAnimations.js';
import initStudioBaby from './studio-baby.js';
import initAtHomeBaby from './at-home-baby.js';

initHeader();
initAbout();
initMaternity();
initTestimonials();
initPhilosophy();
initMemories();
initScroll();
initShowcase();
initStudioBaby();
initAtHomeBaby();
